### ISSUE TITLE
STATUS: Should I be using the develop branch?

### ISSUE THREAD

**Issue by HenrikBengtsson** [pneuvial/c3co#22]
Hi, coming back to this again and finally might give it a real go.  Should I be using the `develop` branch?

**Comment by pneuvial** [comment]
Good!

We created the `intercept` branch in order to address some identifiability issues. I haven't merged it into develop because it is not finalized yet. In the meantime Julien has made a lot of code cleanups on that branch. So I think it's better to use `intercept`.  

I should add that although I haven't been able to work on this for months, we're still willing to finalize this project soon.

**Comment by HenrikBengtsson** [comment]
Got it. So, I'll work with the `intercept` branch then.  I'll troubleshoot, bug fix, PR, ... for that one too.

**Comment by HenrikBengtsson** [comment]
FYI, I'm tidying up a few things in the package (recently the vignettes).  I'm working / pushing to the [`intercept`](https://github.com/pneuvial/c3co/tree/intercept) branch.
