### ISSUE TITLE
Inconsistency in get.W: when M = 2, ncol(Z) = 2 x J (and not J)

### ISSUE THREAD

**Issue by jchiquet** [pneuvial/c3co#64]
From the optimization point of view, solving in W when the signal dimension M is equal to 2 can be achieved by binding <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;(Y^1,&space;Y^2)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;(Y^1,&space;Y^2)" title="(Y^1, Y^2)" /></a> column-wisely and <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;(Z^1)^t,&space;(Z^2)^t" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;(Z^1)^t,&space;(Z^2)^t" title="(Z^1)^t, (Z^2)^t" /></a> row-wisely.

However, in this case, neither `nrow(Z)` nor `ncol(Y)` is equal to J but to 2 x J. Hence, the documentation of the function is inconsistent and then we cannot test reliably for K <= J within the function.

**Comment by HenrikBengtsson** [comment]
Double checking: could it be that we incorrectly use, say, `J <- ncol(Y)` somewhere in the code as the true J?

**Comment by pneuvial** [comment]
From the maths side, I'd say that what we did is correct, ie:

 checking that 2J (= ncol(Y)) is larger than K (= number of subclones) 

is really what we want to check for, because the matrix Z is K x 2J.
So I'd argue it makes sense to keep that sanity check.

From the copy-number side, my intuition is that if we have J < K <= 2J then it may be that 

- the problem is not identifiable from total copy numbers
- the problem is identifiable from minor and major copy numbers

ie again the sanity check K <= 2J makes sense.
